from .integrations import romberg_integration, simpsons_rule, trapezoidal_rule
from .roots_finding import Newton_Raphson, Bisection_Method, Secant_Method
from .interpolation import linear_interpolation, polynomial_interpolation, lagrange_interpolation, neville, cubic_spline_interpolation
from .solving_equations import jacobi_solver, gauss_seidel_solver,condition_number
from .machine_precision import calculate_machine_epsilon
from .graphs import plot_linear_interpolation_graph, plot_polynomial_interpolation_graph, plot_lagrange_interpolation_graph, plot_neville_interpolation_graph, plot_cubic_spline_interpolation_graph, plot_bisection_graph, plot_newtonraphson_graph, plot_secant_graph

